# Generated by Django 4.1 on 2022-11-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0001_initial'),
        ('PostApp', '0005_alter_post_liked_by_alter_post_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='Tag.tag'),
        ),
    ]
