# Generated by Django 4.1 on 2022-11-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0008_post_posted_by_post_tag_alter_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
    ]
