# Generated by Django 4.1 on 2022-11-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_tag_created_at'),
        ('PostApp', '0009_remove_post_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='Tag.tag'),
        ),
    ]
