# Generated by Django 4.1 on 2022-11-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_password2'),
        ('PostApp', '0010_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ManyToManyField(to='User.user'),
        ),
    ]
