# Generated by Django 4.1 on 2022-11-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0012_remove_post_posted_by_post_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
