# Generated by Django 3.2.4 on 2022-11-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0017_auto_20221130_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_likes',
        ),
    ]
