# Generated by Django 3.2.4 on 2022-11-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userprofile_email'),
        ('PostApp', '0019_auto_20221130_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvote_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvoted_post', to='User.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoted_post', to='User.UserProfile'),
        ),
    ]
