# Generated by Django 3.2.4 on 2023-03-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0025_auto_20230312_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
    ]
