# Generated by Django 4.1 on 2022-11-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_alter_post_liked_by_alter_post_posted_by_and_more'),
        ('User', '0002_user_followed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('ifLogged', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
