# Generated by Django 4.1 on 2022-11-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0004_alter_post_liked_by_alter_post_posted_by_and_more'),
        ('User', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
