# Generated by Django 4.1 on 2023-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follow_to_post', models.BooleanField(default=False)),
                ('follow_to_comment', models.BooleanField(default=False)),
                ('follow_to_like', models.BooleanField(default=False)),
                ('general_rules', models.TextField(blank=True, null=True)),
                ('relevant_tags', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTagFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
