# Generated by Django 3.2.4 on 2022-11-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20221120_0849'),
        ('Tag', '0004_alter_tag_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='User.userprofile'),
        ),
        migrations.CreateModel(
            name='UserTagFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='Tag.tag')),
                ('userProfile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='User.userprofile')),
            ],
            options={
                'unique_together': {('userProfile_id', 'following_tag_id')},
            },
        ),
    ]
