# Generated by Django 3.2.4 on 2022-11-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userprofile_email'),
        ('Tag', '0005_auto_20221120_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='User.userprofile'),
        ),
    ]
