# Generated by Django 3.2.4 on 2022-11-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userprofile_email'),
        ('Tag', '0006_alter_tag_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertagfollowing',
            old_name='userProfile_id',
            new_name='followerUser',
        ),
        migrations.AlterUniqueTogether(
            name='usertagfollowing',
            unique_together={('followerUser', 'following_tag_id')},
        ),
    ]
