# Generated by Django 4.1 on 2022-11-05 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PostApp', '0007_remove_post_posted_by_remove_post_tag'),
        ('User', '0005_user_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=10000)),
                ('commented_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('commented_on', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PostApp.post')),
            ],
        ),
    ]
