# Generated by Django 4.1.6 on 2023-04-24 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvote_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='downvoted_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taged_title', to='Tag.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='upvote_users',
            field=models.ManyToManyField(blank=True, default=None, related_name='upvoted_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_on', to='PostApp.post'),
        ),
    ]
