# Generated by Django 4.1.6 on 2023-04-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0003_rename_comment_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='comment_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentor_name',
            new_name='commentor_by',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
