# Generated by Django 4.1 on 2022-11-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_password2'),
        ('Tag', '0001_initial'),
        ('PostApp', '0007_remove_post_posted_by_remove_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='User.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tag.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by', to='User.user'),
        ),
    ]
