# Generated by Django 4.1 on 2022-11-19 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_created_at'),
        ('PostApp', '0011_post_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
    ]
