# Generated by Django 4.1 on 2022-11-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_tag_created_at'),
        ('PostApp', '0013_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tag.tag'),
            preserve_default=False,
        ),
    ]
