# Generated by Django 3.2.4 on 2022-11-30 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_userprofile_email'),
        ('PostApp', '0016_auto_20221120_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_by', to='User.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_by', to='User.userprofile'),
        ),
    ]
