# Generated by Django 3.2.4 on 2022-12-15 11:51

import PostApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0022_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='posts/default.jpg', upload_to=PostApp.models.upload_to, verbose_name='image'),
        ),
    ]
