# Generated by Django 3.2.4 on 2022-12-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0023_alter_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='image',
        ),
    ]
