# Generated by Django 4.1 on 2022-09-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, default='None Rules Applied', max_length=10000)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
