# Generated by Django 4.1 on 2022-11-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_password2'),
        ('Tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='User.user'),
            preserve_default=False,
        ),
    ]
