# Generated by Django 4.1.6 on 2023-04-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cover_photo',
        ),
    ]
