# Generated by Django 4.1 on 2022-09-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
    ]
