# Generated by Django 4.1 on 2022-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
