# Generated by Django 4.1 on 2022-08-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='No paaword:', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='pass', max_length=128),
            preserve_default=False,
        ),
    ]
